### ISSUE TITLE
Miners should see what solutions/shares they found

### ISSUE THREAD

**Issue by Mateikk** [satoshi-pow/SatoshiPoW#2]
### Please describe the feature you'd like to see added.

Miners should see possible solutions/shares with their difficulty indicator that they found while mining. This can especially help new and smaller miners to track their real-time progress, predict how often blocks will arrive or see how close they were to hit a block.

### Is your feature related to a problem, if so please describe it.

Many miners complain about not getting a block in long time. With this, they can see if mining is really in progress or not.

### Describe the solution you'd like

**The solution is**, creating a new line in debug.txt that only shows possible solutions found, means real-time mining information will appear every share is found, like in the traditional mining softwares.

### Describe any alternatives you've considered

**If this uses much CPU, alternatively** a new line can be added to the result of 'getmininginfo', which shows best share found so far.

### Please leave any additional context

An example of what I mean:

`2024-XX-XXTXX:XX:XXZ ThreadStakeMiner(): share #1 found. diff: XX.XXXXXXXXXXXXXX target: CURRENT_NET_DIFF`

Or
```
{
  "blocks": XXXXX,
  "currentblockweight": XXXX,
  "currentblocktx": XXXXX,
  "difficulty": XX.XXXXXXXXXXXXXX,
  "networkhashps": XXXXXXXXX.XXXXXXX,
  "localhashps": XXXXXX,
  "daystofind": XX.XXXXXXXXXXXXXX,
  "cpuloadingpercent": X.X,
  "pooledtx": XXXXX,
  "chain": "main",
  "warnings": "",
  "bestshare": "difficulty of best share/solution"
}
```

**Comment by satoshi-pow** [comment]
A "share" is awarded to members of a mining pool who present a valid partial proof-of-work. 
SatoshiPoW is a pool resistant chain, therefore shares do not exist. You do not submit a partial proof of work. You submit a solution when it has been found. 
The info that resides in the getmininginfo rpc call already give the user the information about their hashrate, network hashrate, and average days to find a block.
Please clarify what you are asking or update the code and submit a pull request to demonstrate.

**Comment by Mateikk** [comment]
> A "share" is awarded to members of a mining pool who present a valid partial proof-of-work. SatoshiPoW is a pool resistant chain, therefore shares do not exist. You do not submit a partial proof of work. You submit a solution when it has been found. The info that resides in the getmininginfo rpc call already give the user the information about their hashrate, network hashrate, and average days to find a block. Please clarify what you are asking or update the code and submit a pull request to demonstrate.

So you mean only valid solutions being sent not the candidate/possible ones, right?
